version: '2'

services:
  db:
    build: arangodb
    ports:
      - 8529:8529
    command: arangod
    environment:
      ARANGO_ROOT_PASSWORD: ${DB_PASSWORD}

  backend:
    build: backend
    ports:
      - 3001:3000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    network_mode: host
