version: '2'

services:
  db:
    container_name: business-chat-db
    build: arangodb
    ports:
      - 8529:8529
    command: arangod
    environment:
      ARANGO_ROOT_PASSWORD: ${DB_PASSWORD}

  backend:
    container_name: business-chat-backend
    build: backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    network_mode: host
    environment:
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: localhost
      DB_PORT: 8529
      PORT: 3001

  frontend:
    container_name: business-chat-frontend
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    network_mode: host
